ALTER TABLE UZMTNOTIFICATION
   DROP CONSTRAINT FK_UZMTNOTI_FK_UZMTNO_UZMTOPTI;

ALTER TABLE UZMTNOTIFICATION
   DROP CONSTRAINT FK_UZMTNOTI_FK_UZMTNO_UZMTNOTI;

ALTER TABLE UZMTOPTION
   DROP CONSTRAINT FK_UZMTOPTI_FK_UZMTOP_UZNTSYST;

DROP TABLE UZMTGROUP CASCADE CONSTRAINTS;

DROP INDEX FK_UZMTNOTIFICATION_TYPE_ID_FK;

DROP INDEX FK_UZMTNOTIFICATION_OPTION_ID_;

DROP TABLE UZMTNOTIFICATION CASCADE CONSTRAINTS;

DROP TABLE UZMTNOTIFICATIONS_TYPE CASCADE CONSTRAINTS;

DROP INDEX FK_UZMTOPTION_SYSTEM_ID_FK;

DROP TABLE UZMTOPTION CASCADE CONSTRAINTS;

DROP TABLE UZNTSYSTEM CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: UZMTGROUP                                             */
/*==============================================================*/
CREATE TABLE UZMTGROUP (
   UZMTGROUP_ID         INTEGER               NOT NULL,
   UZMTGROUP_NAME       CHAR(200),
   UZMTGROUP_DESCRIPCION CHAR(200),
   UZMTGROUP_SCRIPT     CHAR(200),
   UZMTGROUP_PARAMETRO  SMALLINT,
   UZMTGROUP_ACTIVE     SMALLINT,
   UZMTGROUP_CREATION_DATE TIMESTAMP,
   UZMTGROUP_USER_CREATION CHAR(200),
   UZMTGROUP_CHANGE_DATE TIMESTAMP,
   UZMTGROUP_USER_CHANGE CHAR(200),
   CONSTRAINT PK_UZMTGROUP PRIMARY KEY (UZMTGROUP_ID)
);

/*==============================================================*/
/* Table: UZMTNOTIFICATION                                      */
/*==============================================================*/
CREATE TABLE UZMTNOTIFICATION (
   UZMTNOTIFICATION_ID  INTEGER               NOT NULL,
   UZMTNOTIFICATION_TYPE_ID INTEGER,
   UZMTOPTION_ID        INTEGER,
   UZMTNOTIFICATION_MESSAGE CHAR(200),
   UZMTNOTIFICATION_RECEIVER CHAR(200),
   UZMTNOTIFICATION_ACTIVE SMALLINT,
   UZMTNOTIFICATION_READ SMALLINT,
   UZMTNOTIFICATION_READ_DATE TIMESTAMP,
   UZMTNOTIFICATION_IP  CHAR(200),
   UZMTNOTIFICATION_AGENTE CHAR(200),
   UZMTNOTIFICATION_CREATION_DATE TIMESTAMP,
   UZMTNOTIFICATION_USER_CREATION CHAR(200),
   UZMTNOTIFICATION_CHANGE_DATE TIMESTAMP,
   UZMTNOTIFICATION_USER_CHANGE CHAR(200),
   CONSTRAINT PK_UZMTNOTIFICATION PRIMARY KEY (UZMTNOTIFICATION_ID)
);

/*==============================================================*/
/* Index: FK_UZMTNOTIFICATION_OPTION_ID_                        */
/*==============================================================*/
CREATE INDEX FK_UZMTNOTIFICATION_OPTION_ID_ ON UZMTNOTIFICATION (
   UZMTOPTION_ID ASC
);

/*==============================================================*/
/* Index: FK_UZMTNOTIFICATION_TYPE_ID_FK                        */
/*==============================================================*/
CREATE INDEX FK_UZMTNOTIFICATION_TYPE_ID_FK ON UZMTNOTIFICATION (
   UZMTNOTIFICATION_TYPE_ID ASC
);

/*==============================================================*/
/* Table: UZMTNOTIFICATIONS_TYPE                                */
/*==============================================================*/
CREATE TABLE UZMTNOTIFICATIONS_TYPE (
   UZMTNOTIFICATION_TYPE_ID INTEGER               NOT NULL,
   UZMTNOTIFICATION_TYPE_NAME CHAR(200),
   UZMTNOTIFICATION_TYPE_ACTIVE SMALLINT,
   UZMTNOTIFICATION_TYPE_CREATION TIMESTAMP,
   UZMTNOTIFICATION_TYPE_USER_CREATION CHAR(200),
   UZMTNOTIFICATION_TYPE_CHANGE_DATE TIMESTAMP,
   UZMTNOTIFICATION_TYPE_USER_CHANGE CHAR(200),
   CONSTRAINT PK_UZMTNOTIFICATIONS_TYPE PRIMARY KEY (UZMTNOTIFICATION_TYPE_ID)
);

/*==============================================================*/
/* Table: UZMTOPTION                                            */
/*==============================================================*/
CREATE TABLE UZMTOPTION (
   UZMTOPTION_ID        INTEGER               NOT NULL,
   UZNTSYSTEM_ID        INTEGER,
   UZMTOPTION_CODE      CHAR(200),
   UZMTOPTION_NAME      CHAR(200),
   UZMTOPTION_SYSTEM_ID INTEGER,
   UZMTOPTION_ACTIVE    SMALLINT,
   UZMTOPTION_CREATION_DATE TIMESTAMP,
   UZMTOPTION_USER_CREATION CHAR(200),
   UZMTOPTION_CHANGE_DATE TIMESTAMP,
   UZMTOPTION_USER_CHANGE CHAR(200),
   CONSTRAINT PK_UZMTOPTION PRIMARY KEY (UZMTOPTION_ID)
);

/*==============================================================*/
/* Index: FK_UZMTOPTION_SYSTEM_ID_FK                            */
/*==============================================================*/
CREATE INDEX FK_UZMTOPTION_SYSTEM_ID_FK ON UZMTOPTION (
   UZNTSYSTEM_ID ASC
);

/*==============================================================*/
/* Table: UZNTSYSTEM                                            */
/*==============================================================*/
CREATE TABLE UZNTSYSTEM (
   UZNTSYSTEM_ID        INTEGER               NOT NULL,
   UZMTSYSTEM_CODE      CHAR(200),
   UZMTSYSTEM_NAME      CHAR(256),
   UZMTSYSTEM_ACTIVE    SMALLINT,
   UZMTSYSTEM_CREATION_DATE TIMESTAMP,
   UZMTSYSTEM_USER_CREATION CHAR(200),
   UZMTSYSTEM_CHANGE_DATE TIMESTAMP,
   UZMTSYSTEM_USER_CHANGE CHAR(200),
   CONSTRAINT PK_UZNTSYSTEM PRIMARY KEY (UZNTSYSTEM_ID)
);

ALTER TABLE UZMTNOTIFICATION
   ADD CONSTRAINT FK_UZMTNOTI_FK_UZMTNO_UZMTOPTI FOREIGN KEY (UZMTOPTION_ID)
      REFERENCES UZMTOPTION (UZMTOPTION_ID);

ALTER TABLE UZMTNOTIFICATION
   ADD CONSTRAINT FK_UZMTNOTI_FK_UZMTNO_UZMTNOTI FOREIGN KEY (UZMTNOTIFICATION_TYPE_ID)
      REFERENCES UZMTNOTIFICATIONS_TYPE (UZMTNOTIFICATION_TYPE_ID);

ALTER TABLE UZMTOPTION
   ADD CONSTRAINT FK_UZMTOPTI_FK_UZMTOP_UZNTSYST FOREIGN KEY (UZNTSYSTEM_ID)
      REFERENCES UZNTSYSTEM (UZNTSYSTEM_ID);
