-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 0.9.4
-- PostgreSQL version: 13.0
-- Project Site: pgmodeler.io
-- Model Author: ---
-- object: "UTIC" | type: ROLE --
-- DROP ROLE IF EXISTS "UTIC";
CREATE ROLE "UTIC" WITH 
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	LOGIN
	REPLICATION
	ENCRYPTED PASSWORD '********';
-- ddl-end --


-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: test3 | type: DATABASE --
-- DROP DATABASE IF EXISTS test3;
CREATE DATABASE test3
	ENCODING = 'UTF8'
	LC_COLLATE = 'Spanish_Ecuador.1252'
	LC_CTYPE = 'Spanish_Ecuador.1252'
	TABLESPACE = pg_default
	OWNER = postgres;
-- ddl-end --


-- object: "UZNT" | type: SCHEMA --
-- DROP SCHEMA IF EXISTS "UZNT" CASCADE;
CREATE SCHEMA "UZNT";
-- ddl-end --
ALTER SCHEMA "UZNT" OWNER TO postgres;
-- ddl-end --

SET search_path TO pg_catalog,public,"UZNT";
-- ddl-end --

-- object: "UZNT"."UZNTSYSTEM" | type: TABLE --
-- DROP TABLE IF EXISTS "UZNT"."UZNTSYSTEM" CASCADE;
CREATE TABLE "UZNT"."UZNTSYSTEM" (
	"UZNTSYSTEM_ID" integer NOT NULL,
	"UZNTSYSTEM_CODE" character varying,
	"UZNTSYSTEM_NAME" character varying,
	"UZNTSYSTEM_ACTIVE" boolean,
	"UZNTSYSTEM_CREATION_DATE" timestamp,
	"UZNTSYSTEM_USER_CREATION" character varying,
	"UZNTSYSTEM_CHANGE_DATE" timestamp,
	"UZNTSYSTEM_USER_CHANGE" character varying,
	CONSTRAINT "PK_SYSTEM" PRIMARY KEY ("UZNTSYSTEM_ID"),
	CONSTRAINT "UNIQ_UZMTSYSTEM_CODE" UNIQUE ("UZNTSYSTEM_CODE")
);
-- ddl-end --
COMMENT ON TABLE "UZNT"."UZNTSYSTEM" IS E'systema de donde se esta enviando la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_ID" IS E'identificador de la tabla de sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_CODE" IS E'es un codigo unico parta cada sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_NAME" IS E'Nombre asignado para el sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_ACTIVE" IS E'muestra si esta activo o desactivo el sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_CREATION_DATE" IS E'es la fecha de creacion del sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_USER_CREATION" IS E'el usuario que creo el sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_CHANGE_DATE" IS E'la fecha cuando fua actualizado el sistema';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_USER_CHANGE" IS E'el usuario que actualizo el registro del sistema';
-- ddl-end --
COMMENT ON CONSTRAINT "PK_SYSTEM" ON "UZNT"."UZNTSYSTEM"  IS E'Llave primaria del sistemas';
-- ddl-end --
COMMENT ON CONSTRAINT "UNIQ_UZMTSYSTEM_CODE" ON "UZNT"."UZNTSYSTEM"  IS E'EL CODIGO DEBE SER DIFERENTE DE TODOS';
-- ddl-end --
ALTER TABLE "UZNT"."UZNTSYSTEM" OWNER TO "UTIC";
-- ddl-end --

-- object: "UZNT"."UZNTOPTION" | type: TABLE --
-- DROP TABLE IF EXISTS "UZNT"."UZNTOPTION" CASCADE;
CREATE TABLE "UZNT"."UZNTOPTION" (
	"UZNTOPTION_ID" integer NOT NULL,
	"UZNTOPTION_SYSTEM_ID" integer,
	"UZNTOPTION_CODE" character varying,
	"UZNTOPTION_NAME" character varying,
	"UZNTOPTION_ACTIVE" boolean,
	"UZNTOPTION_CREATION_DATE" timestamp,
	"UZNTOPTION_USER_CREATION" character varying,
	"UZNTOPTION_CHANGE_DATE" timestamp,
	"UZNTOPTION_USER_CHANGE" character varying,
	CONSTRAINT "PK_OPTION" PRIMARY KEY ("UZNTOPTION_ID"),
	CONSTRAINT "UNIQ_UZNTOPTION_CODE" UNIQUE ("UZNTOPTION_CODE")
);
-- ddl-end --
COMMENT ON TABLE "UZNT"."UZNTOPTION" IS E'se indica la opcion de la notificacion y a que sistema pertenece';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_ID" IS E'Identificador de la tabla option';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_SYSTEM_ID" IS E'llave foranea en relacion con la tabla sistem';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_CODE" IS E'codigo unico de la tabla option';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_NAME" IS E'nombre de la opcion a seleccionar';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_ACTIVE" IS E'indicador si la option esta activa o no';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_CREATION_DATE" IS E'es la fecha de creacion de la opcion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_USER_CREATION" IS E'el usuario que creo la opcion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_CHANGE_DATE" IS E'la fecha cuando fua actualizado la opcion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTOPTION"."UZNTOPTION_USER_CHANGE" IS E'el usuario que actualizo el registro de la opcion';
-- ddl-end --
COMMENT ON CONSTRAINT "PK_OPTION" ON "UZNT"."UZNTOPTION"  IS E'LLAVE PRIMARIA DE LA TABLA PRIMARIA';
-- ddl-end --
COMMENT ON CONSTRAINT "UNIQ_UZNTOPTION_CODE" ON "UZNT"."UZNTOPTION"  IS E'CODIGO UNICO PARA OPCIONES';
-- ddl-end --
ALTER TABLE "UZNT"."UZNTOPTION" OWNER TO "UTIC";
-- ddl-end --

-- object: "UZNT"."UZNTNOTIFICATION_TYPE" | type: TABLE --
-- DROP TABLE IF EXISTS "UZNT"."UZNTNOTIFICATION_TYPE" CASCADE;
CREATE TABLE "UZNT"."UZNTNOTIFICATION_TYPE" (
	"UZNTNOTIFICATION_TYPE_ID" integer NOT NULL,
	"UZNTNOTIFICATION_TYPE_NAME" character varying,
	"UZNTNOTIFICATION_TYPE_ACTIVE" boolean,
	"UZNTNOTIFICATION_TYPE_CREATION_DATE" timestamp,
	"UZNTNOTIFICATION_TYPE_USER_CREATION" character varying,
	"UZNTNOTIFICATION_TYPE_CHANGE_DATE" timestamp,
	"UZNTNOTIFICATION_TYPE_USER_CHANGE" character varying,
	CONSTRAINT "PK_NOTIFICATION_TYPE" PRIMARY KEY ("UZNTNOTIFICATION_TYPE_ID")
);
-- ddl-end --
COMMENT ON TABLE "UZNT"."UZNTNOTIFICATION_TYPE" IS E'tabla para indicar el tipoo de notificacion indicado';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_ID" IS E'identificador de la tabla tipo de notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_NAME" IS E'nombre del tipo de notificacion asignada a la misma';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_ACTIVE" IS E'indicar si el tipo de notificacion esta activo';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_CREATION_DATE" IS E'es la fecha de creacion del tipo de notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_USER_CREATION" IS E'el usuario que creo el tipo de notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_CHANGE_DATE" IS E'la fecha cuando fua actualizado el tipo de notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_USER_CHANGE" IS E'el usuario que actualizo el registro del tipo de notificacion';
-- ddl-end --
COMMENT ON CONSTRAINT "PK_NOTIFICATION_TYPE" ON "UZNT"."UZNTNOTIFICATION_TYPE"  IS E'llave primaria de la tabla de tipo de notificaciones';
-- ddl-end --
ALTER TABLE "UZNT"."UZNTNOTIFICATION_TYPE" OWNER TO "UTIC";
-- ddl-end --

-- object: "UZNT"."UZNTNOTIFICATION" | type: TABLE --
-- DROP TABLE IF EXISTS "UZNT"."UZNTNOTIFICATION" CASCADE;
CREATE TABLE "UZNT"."UZNTNOTIFICATION" (
	"UZNTNOTIFICATION_ID" integer NOT NULL,
	"UZNTNOTIFICATION_OPTION_ID" integer NOT NULL,
	"UZNTNOTIFICATION_TYPE_ID" integer NOT NULL,
	"UZNTNOTIFICATION_SUBJECT" character varying(200),
	"UZNTNOTIFICATION_MESSAGE" character varying(500),
	"UZNTNOTIFICATION_RECEIVER" character varying,
	"UZNTNOTIFICATION_IP" character varying,
	"UZNTNOTIFICATION_AGENTE" character varying,
	"UZNTNOTIFICATION_ACTIVE" boolean,
	"UZNTNOTIFICATION_READ" boolean,
	"UZNTNOTIFICATION_READ_DATE" timestamp,
	"UZNTNOTIFICATION_CREATION_DATE" timestamp,
	"UZNTNOTIFICATION_USER_CREATION" character varying,
	"UZNTNOTIFICATION_CHANGE_DATE" timestamp,
	"UZNTNOTIFICATION_USER_CHANGE" character varying,
	CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("UZNTNOTIFICATION_ID")
);
-- ddl-end --
COMMENT ON TABLE "UZNT"."UZNTNOTIFICATION" IS E'todos los valores de la notificacion correspondiente';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_ID" IS E'identificador de la fila de la tabla de notificaciones';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_OPTION_ID" IS E'relacion que existe en la tabla notificacion con la opcion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_TYPE_ID" IS E'relacion con el tipo de notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_SUBJECT" IS E'EL ASUNTO QUE VIENE INCLUIDO EN LA NOTIFICACION';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_MESSAGE" IS E'el menaje que va incluido en la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_RECEIVER" IS E'a quien va dirijido la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_IP" IS E'la ip desde donde se abre la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_AGENTE" IS E'el servidor desde donde se abrio la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_ACTIVE" IS E'se muestra si la notificacion esta activa o no';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_READ" IS E'muestra si la notificacion fue leida o no';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_READ_DATE" IS E'la fecha y la hora en la que se ha leido la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_CREATION_DATE" IS E'fecha en la que se creo este registro';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_USER_CREATION" IS E'el usuario que creo la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_CHANGE_DATE" IS E'la fecha cuando fua actualizado la notificacion';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_USER_CHANGE" IS E'el usuario que actualizo el registro de la notificacion';
-- ddl-end --
COMMENT ON CONSTRAINT "PK_NOTIFICATION" ON "UZNT"."UZNTNOTIFICATION"  IS E'llave primaria de la tabla notificacion';
-- ddl-end --
ALTER TABLE "UZNT"."UZNTNOTIFICATION" OWNER TO "UTIC";
-- ddl-end --

-- object: "UZNT"."UZNTGROUP" | type: TABLE --
-- DROP TABLE IF EXISTS "UZNT"."UZNTGROUP" CASCADE;
CREATE TABLE "UZNT"."UZNTGROUP" (
	"UZNTGROUP_ID" integer NOT NULL,
	"UZNTGROUP_NAME" character varying,
	"UZNTGROUP_DESCRIPCION" character varying,
	"UZNTGROUP_SCRIPT" character varying,
	"UZNTGROUP_PARAMETRO" boolean,
	"UZNTGROUP_ACTIVE" boolean,
	"UZNTGROUP_CREATION_DATE" timestamp,
	"UZNTGROUP_USER_CREATION" character varying,
	"UZNTGROUP_CHANGE_DATE" timestamp,
	"UZNTGROUP_USER_CHANGE" character varying,
	CONSTRAINT "PK_GROUP" PRIMARY KEY ("UZNTGROUP_ID")
);
-- ddl-end --
COMMENT ON TABLE "UZNT"."UZNTGROUP" IS E'rango de grupos asignados';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_ID" IS E'identificado del regitro de datos en la tabla grupos';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_NAME" IS E'asignacion del nombre del grupo';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_DESCRIPCION" IS E'respectiva descripcion del grupo designado';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_SCRIPT" IS E'SQL de la consulta en la base de datos';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_PARAMETRO" IS E'indicar si el sql tiene parametros o no';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_ACTIVE" IS E'indica si el grupo esta en constancia o no';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_CREATION_DATE" IS E'es la fecha de creacion del grupo';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_USER_CREATION" IS E'el usuario que creo el grupo';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_CHANGE_DATE" IS E'la fecha cuando fua actualizado el grupo';
-- ddl-end --
COMMENT ON COLUMN "UZNT"."UZNTGROUP"."UZNTGROUP_USER_CHANGE" IS E'el usuario que actualizo el registro del grupo';
-- ddl-end --
COMMENT ON CONSTRAINT "PK_GROUP" ON "UZNT"."UZNTGROUP"  IS E'llave primaria de la tabla grupo';
-- ddl-end --
ALTER TABLE "UZNT"."UZNTGROUP" OWNER TO "UTIC";
-- ddl-end --

-- object: "UZNT"."UZMSSYSTEM_ID" | type: SEQUENCE --
-- ALTER TABLE "UZNT"."UZNTSYSTEM" DROP SEQUENCE IF EXISTS "UZNT"."UZMSSYSTEM_ID" CASCADE;
CREATE SEQUENCE "UZNT"."UZMSSYSTEM_ID"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY "UZNT"."UZNTSYSTEM"."UZNTSYSTEM_ID";

ALTER TABLE "UZNT"."UZNTSYSTEM" ALTER COLUMN "UZNTSYSTEM_ID"
 SET DEFAULT nextval('"UZNT"."UZMSSYSTEM_ID"'::regclass);
-- ddl-end --
ALTER SEQUENCE "UZNT"."UZMSSYSTEM_ID" OWNER TO "UTIC";
-- ddl-end --
COMMENT ON SEQUENCE "UZNT"."UZMSSYSTEM_ID" IS E'SECUENCIA DE SYSTEM';
-- ddl-end --

-- object: "UZNT"."UZMSOPTION_ID" | type: SEQUENCE --
-- ALTER TABLE "UZNT"."UZNTOPTION" DROP SEQUENCE IF EXISTS "UZNT"."UZMSOPTION_ID" CASCADE;
CREATE SEQUENCE "UZNT"."UZMSOPTION_ID"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY "UZNT"."UZNTOPTION"."UZNTOPTION_ID";

ALTER TABLE "UZNT"."UZNTOPTION" ALTER COLUMN "UZNTOPTION_ID"
 SET DEFAULT nextval('"UZNT"."UZMSOPTION_ID"'::regclass);
-- ddl-end --
ALTER SEQUENCE "UZNT"."UZMSOPTION_ID" OWNER TO "UTIC";
-- ddl-end --
COMMENT ON SEQUENCE "UZNT"."UZMSOPTION_ID" IS E'SECUENCIA DE OPTION';
-- ddl-end --

-- object: "UZNT"."UZMSNOTIFICATION_TYPE_ID" | type: SEQUENCE --
-- ALTER TABLE "UZNT"."UZNTNOTIFICATION_TYPE" DROP SEQUENCE IF EXISTS "UZNT"."UZMSNOTIFICATION_TYPE_ID" CASCADE;
CREATE SEQUENCE "UZNT"."UZMSNOTIFICATION_TYPE_ID"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY "UZNT"."UZNTNOTIFICATION_TYPE"."UZNTNOTIFICATION_TYPE_ID";

ALTER TABLE "UZNT"."UZNTNOTIFICATION_TYPE" ALTER COLUMN "UZNTNOTIFICATION_TYPE_ID"
 SET DEFAULT nextval('"UZNT"."UZMSNOTIFICATION_TYPE_ID"'::regclass);
-- ddl-end --
ALTER SEQUENCE "UZNT"."UZMSNOTIFICATION_TYPE_ID" OWNER TO "UTIC";
-- ddl-end --
COMMENT ON SEQUENCE "UZNT"."UZMSNOTIFICATION_TYPE_ID" IS E'SECUENCIA DE TIPOS DE NOTIFICACIONES';
-- ddl-end --

-- object: "UZNT"."UZMSGROUP_ID" | type: SEQUENCE --
-- ALTER TABLE "UZNT"."UZNTGROUP" DROP SEQUENCE IF EXISTS "UZNT"."UZMSGROUP_ID" CASCADE;
CREATE SEQUENCE "UZNT"."UZMSGROUP_ID"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY "UZNT"."UZNTGROUP"."UZNTGROUP_ID";

ALTER TABLE "UZNT"."UZNTGROUP" ALTER COLUMN "UZNTGROUP_ID"
 SET DEFAULT nextval('"UZNT"."UZMSGROUP_ID"'::regclass);
-- ddl-end --
ALTER SEQUENCE "UZNT"."UZMSGROUP_ID" OWNER TO "UTIC";
-- ddl-end --
COMMENT ON SEQUENCE "UZNT"."UZMSGROUP_ID" IS E'SECUENCIA DE GRUPOS';
-- ddl-end --

-- object: "UZNT"."UZMSNOTIFICATION_ID" | type: SEQUENCE --
-- ALTER TABLE "UZNT"."UZNTNOTIFICATION" DROP SEQUENCE IF EXISTS "UZNT"."UZMSNOTIFICATION_ID" CASCADE;
CREATE SEQUENCE "UZNT"."UZMSNOTIFICATION_ID"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START WITH 1
	CACHE 1
	NO CYCLE
	OWNED BY "UZNT"."UZNTNOTIFICATION"."UZNTNOTIFICATION_ID";

ALTER TABLE "UZNT"."UZNTNOTIFICATION" ALTER COLUMN "UZNTNOTIFICATION_ID"
 SET DEFAULT nextval('"UZNT"."UZMSNOTIFICATION_ID"'::regclass);
-- ddl-end --
ALTER SEQUENCE "UZNT"."UZMSNOTIFICATION_ID" OWNER TO "UTIC";
-- ddl-end --
COMMENT ON SEQUENCE "UZNT"."UZMSNOTIFICATION_ID" IS E'SECUENCIA DE NOTIFICACIONES';
-- ddl-end --

-- object: "FK_SYSTEM" | type: CONSTRAINT --
-- ALTER TABLE "UZNT"."UZNTOPTION" DROP CONSTRAINT IF EXISTS "FK_SYSTEM" CASCADE;
ALTER TABLE "UZNT"."UZNTOPTION" ADD CONSTRAINT "FK_SYSTEM" FOREIGN KEY ("UZNTOPTION_SYSTEM_ID")
REFERENCES "UZNT"."UZNTSYSTEM" ("UZNTSYSTEM_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "FK_SYSTEM" ON "UZNT"."UZNTOPTION"  IS E'LLAVE FORANEA RELACIONADO CON SISTEMA';
-- ddl-end --


-- object: "FK_OPTION" | type: CONSTRAINT --
-- ALTER TABLE "UZNT"."UZNTNOTIFICATION" DROP CONSTRAINT IF EXISTS "FK_OPTION" CASCADE;
ALTER TABLE "UZNT"."UZNTNOTIFICATION" ADD CONSTRAINT "FK_OPTION" FOREIGN KEY ("UZNTNOTIFICATION_OPTION_ID")
REFERENCES "UZNT"."UZNTOPTION" ("UZNTOPTION_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "FK_OPTION" ON "UZNT"."UZNTNOTIFICATION"  IS E'llave foranea een relacion con la tabla de opcion';
-- ddl-end --


-- object: "FK_NOTIFICATION_TYPE" | type: CONSTRAINT --
-- ALTER TABLE "UZNT"."UZNTNOTIFICATION" DROP CONSTRAINT IF EXISTS "FK_NOTIFICATION_TYPE" CASCADE;
ALTER TABLE "UZNT"."UZNTNOTIFICATION" ADD CONSTRAINT "FK_NOTIFICATION_TYPE" FOREIGN KEY ("UZNTNOTIFICATION_TYPE_ID")
REFERENCES "UZNT"."UZNTNOTIFICATION_TYPE" ("UZNTNOTIFICATION_TYPE_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "FK_NOTIFICATION_TYPE" ON "UZNT"."UZNTNOTIFICATION"  IS E'llave foranea del tipo de notificacion';
-- ddl-end --


-- object: "grant_CU_eb94f049ac" | type: PERMISSION --
GRANT CREATE,USAGE
   ON SCHEMA public
   TO postgres;
-- ddl-end --

-- object: "grant_CU_cd8e46e7b6" | type: PERMISSION --
GRANT CREATE,USAGE
   ON SCHEMA public
   TO PUBLIC;
-- ddl-end --


