-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 0.9.4
-- PostgreSQL version: 13.0
-- Project Site: pgmodeler.io
-- Model Author: ---

-- Database creation must be performed outside a multi lined SQL file. 
-- These commands were put in this file only as a convenience.
-- 
-- object: new_database | type: DATABASE --
-- DROP DATABASE IF EXISTS new_database;
-- CREATE DATABASE new_database;
-- ddl-end --


-- object: "UZMT" | type: SCHEMA --
-- DROP SCHEMA IF EXISTS "UZMT" CASCADE;
CREATE SCHEMA "UZMT";
-- ddl-end --
ALTER SCHEMA "UZMT" OWNER TO postgres;
-- ddl-end --

SET search_path TO pg_catalog,public,"UZMT";
-- ddl-end --

-- object: "UZMT"."UZMTSYSTEM" | type: TABLE --
-- DROP TABLE IF EXISTS "UZMT"."UZMTSYSTEM" CASCADE;
CREATE TABLE "UZMT"."UZMTSYSTEM" (
	"UZMTSYSTEM_ID" serial NOT NULL,
	"UZMTSYSTEM_CODE" character varying,
	"UZMTSYSTEM_NAME" character varying,
	"UZMTSYSTEM_ACTIVE" boolean,
	"UZMTSYSTEM_CREATION_DATE" date,
	"UZMTSYSTEM_USER_CREATION" character varying,
	"UZMTSYSTEM_CHANGE_DATE" date,
	"UZMTSYSTEM_USER_CHANGE" character varying,
	CONSTRAINT "PK_SYSTEM" PRIMARY KEY ("UZMTSYSTEM_ID")
);
-- ddl-end --
ALTER TABLE "UZMT"."UZMTSYSTEM" OWNER TO postgres;
-- ddl-end --

-- object: "UZMT"."UZMTOPTION" | type: TABLE --
-- DROP TABLE IF EXISTS "UZMT"."UZMTOPTION" CASCADE;
CREATE TABLE "UZMT"."UZMTOPTION" (
	"UZMTOPTION_ID" serial NOT NULL,
	"UZMTOPTION_CODE" character varying,
	"UZMTOPTION_NAME" character varying,
	"UZMTOPTION_SYSTEM_ID" integer,
	"UZMTOPTION_ACTIVE" boolean,
	"UZMTOPTION_CREATION_DATE" date,
	"UZMTOPTION_USER_CREATION" character varying,
	"UZMTOPTION_CHANGE_DATE" date,
	"UZMTOPTION_USER_CHANGE" character varying,
	CONSTRAINT "PK_OPTION" PRIMARY KEY ("UZMTOPTION_ID")
);
-- ddl-end --
ALTER TABLE "UZMT"."UZMTOPTION" OWNER TO postgres;
-- ddl-end --

-- object: "UZMT"."UZMTNOTIFICATION_TYPE" | type: TABLE --
-- DROP TABLE IF EXISTS "UZMT"."UZMTNOTIFICATION_TYPE" CASCADE;
CREATE TABLE "UZMT"."UZMTNOTIFICATION_TYPE" (
	"UZMTNOTIFICATION_TYPE_ID" serial NOT NULL,
	"UZMTNOTIFICATION_TYPE_NAME" character varying,
	"UZMTNOTIFICATION_TYPE_ACTIVE" boolean,
	"UZMTNOTIFICATION_TYPE_CREATION_DATE" date,
	"UZMTNOTIFICATION_TYPE_USER_CREATION" character varying,
	"UZMTNOTIFICATION_TYPE_CHANGE_DATE" date,
	"UZMTNOTIFICATION_TYPE_USER_CHANGE" character varying,
	CONSTRAINT "PK_NOTIFICATION_TYPE" PRIMARY KEY ("UZMTNOTIFICATION_TYPE_ID")
);
-- ddl-end --
ALTER TABLE "UZMT"."UZMTNOTIFICATION_TYPE" OWNER TO postgres;
-- ddl-end --

-- object: "UZMT"."UZMTNOTIFICATION" | type: TABLE --
-- DROP TABLE IF EXISTS "UZMT"."UZMTNOTIFICATION" CASCADE;
CREATE TABLE "UZMT"."UZMTNOTIFICATION" (
	"UZMTNOTIFICATION_ID" serial NOT NULL,
	"UZMTNOTIFICATION_MESSAGE" character varying,
	"UZMTNOTIFICATION_RECEIVER" character varying,
	"UZMTNOTIFICATION_OPTION_ID" integer,
	"UZMTNOTIFICATION_TYPE_ID" integer,
	"UZMTNOTIFICATION_ACTIVE" boolean,
	"UZMTNOTIFICATION_READ" boolean,
	"UZMTNOTIFICATION_READ_DATE" date,
	"UZMTNOTIFICATION_CREATION_DATE" date,
	"UZMTNOTIFICATION_USER_CREATION" character varying,
	"UZMTNOTIFICATION_CHANGE_DATE" date,
	"UZMTNOTIFICATION_USER_CHANGE" character varying,
	"UZMTNOTIFICATION_IP" character varying,
	"UZMTNOTIFICATION_AGENTE" character varying,
	CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("UZMTNOTIFICATION_ID")
);
-- ddl-end --
ALTER TABLE "UZMT"."UZMTNOTIFICATION" OWNER TO postgres;
-- ddl-end --

-- object: "UZMT"."UZMTGROUP" | type: TABLE --
-- DROP TABLE IF EXISTS "UZMT"."UZMTGROUP" CASCADE;
CREATE TABLE "UZMT"."UZMTGROUP" (
	"UZMTGROUP_ID" serial NOT NULL,
	"UZMTGROUP_NAME" character varying,
	"UZMTGROUP_DESCRIPCION" character varying,
	"UZMTGROUP_SCRIPT" character varying,
	"UZMTGROUP_PARAMETRO" boolean,
	"UZMTGROUP_ACTIVE" boolean,
	"UZMTGROUP_CREATION_DATE" date,
	"UZMTGROUP_USER_CREATION" character varying,
	"UZMTGROUP_CHANGE_DATE" date,
	"UZMTGROUP_USER_CHANGE" character varying,
	CONSTRAINT "PK_GROUP" PRIMARY KEY ("UZMTGROUP_ID")
);
-- ddl-end --
ALTER TABLE "UZMT"."UZMTGROUP" OWNER TO postgres;
-- ddl-end --

-- object: "FK_SYSTEM" | type: CONSTRAINT --
-- ALTER TABLE "UZMT"."UZMTOPTION" DROP CONSTRAINT IF EXISTS "FK_SYSTEM" CASCADE;
ALTER TABLE "UZMT"."UZMTOPTION" ADD CONSTRAINT "FK_SYSTEM" FOREIGN KEY ("UZMTOPTION_SYSTEM_ID")
REFERENCES "UZMT"."UZMTSYSTEM" ("UZMTSYSTEM_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: "FK_OPTION" | type: CONSTRAINT --
-- ALTER TABLE "UZMT"."UZMTNOTIFICATION" DROP CONSTRAINT IF EXISTS "FK_OPTION" CASCADE;
ALTER TABLE "UZMT"."UZMTNOTIFICATION" ADD CONSTRAINT "FK_OPTION" FOREIGN KEY ("UZMTNOTIFICATION_OPTION_ID")
REFERENCES "UZMT"."UZMTOPTION" ("UZMTOPTION_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: "FK_NOTIFICATION_TYPE" | type: CONSTRAINT --
-- ALTER TABLE "UZMT"."UZMTNOTIFICATION" DROP CONSTRAINT IF EXISTS "FK_NOTIFICATION_TYPE" CASCADE;
ALTER TABLE "UZMT"."UZMTNOTIFICATION" ADD CONSTRAINT "FK_NOTIFICATION_TYPE" FOREIGN KEY ("UZMTNOTIFICATION_TYPE_ID")
REFERENCES "UZMT"."UZMTNOTIFICATION_TYPE" ("UZMTNOTIFICATION_TYPE_ID") MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --